# Generated by Django 3.1.3 on 2020-11-05 13:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id_product', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('image_name', models.CharField(max_length=50)),
                ('total_number', models.IntegerField(default=1)),
                ('weight', models.IntegerField(default=1000)),
                ('statement', models.CharField(choices=[('T', 'Full'), ('F', 'Empety')], max_length=1)),
                ('off_percent', models.IntegerField(max_length=2)),
                ('type_product', models.CharField(choices=[('C', 'Chicken'), ('M', 'Meat'), ('F', 'Fish'), ('T', 'Turkey'), ('S', 'Special'), ('E', 'else')], max_length=1)),
                ('suggestion', models.CharField(choices=[('T', 'Suggest'), ('F', 'Normal')], max_length=1)),
                ('ommit', models.CharField(choices=[('T', 'active'), ('F', 'ommit')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('total', models.IntegerField()),
                ('day', models.CharField(help_text='[Sat , Sun , Mon , Tue , Wed , Thu , Fri]', max_length=3)),
                ('month', models.CharField(help_text='Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec', max_length=3)),
                ('day_month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('deliver', models.CharField(choices=[('T', 'deliver'), ('F', "don't deliver")], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app1.user')),
            ],
        ),
    ]
