# Generated by Django 3.1.3 on 2020-11-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seconde',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='off_percent',
            field=models.IntegerField(),
        ),
    ]
