# Generated by Django 3.1.3 on 2020-11-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app1', '0002_auto_20201105_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_name',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/retial_app1/image/index.png', upload_to='media/retial_app1/image'),
        ),
    ]
