# Generated by Django 3.1.3 on 2020-11-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app1', '0004_auto_20201109_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='retial_app1/media/image/index.png', upload_to='retail_app1/media/image'),
        ),
    ]
