# Generated by Django 3.1.3 on 2020-11-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app1', '0006_auto_20201109_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reg_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('m', 'men'), ('w', 'women')], default='men', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/media/index.png', upload_to='static/media'),
        ),
    ]
