# Generated by Django 3.1.3 on 2020-11-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app1', '0008_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=' ...'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_product',
            field=models.CharField(choices=[('C', 'Chicken'), ('M', 'Meat'), ('F', 'Fish'), ('T', 'Turkey'), ('E', 'else')], max_length=1),
        ),
    ]
