# Generated by Django 3.1.3 on 2020-11-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app1', '0010_auto_20201115_0607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='prod_name',
        ),
    ]
