# Generated by Django 3.1.3 on 2020-11-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app1', '0011_auto_20201115_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prod_name',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
