# Generated by Django 3.1.3 on 2020-11-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app1', '0012_auto_20201115_0823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='prod_name',
            new_name='username',
        ),
    ]
