# Generated by Django 3.1.3 on 2020-11-15 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app1', '0014_auto_20201115_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_key',
        ),
    ]
