# Generated by Django 3.1.3 on 2020-11-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app1', '0018_auto_20201115_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_EN',
            field=models.CharField(default='product', max_length=50),
        ),
    ]
