# Generated by Django 3.1.3 on 2020-11-17 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app1', '0019_product_name_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('day', models.CharField(help_text='[Sat , Sun , Mon , Tue , Wed , Thu , Fri]', max_length=3)),
                ('month', models.CharField(help_text='[Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]', max_length=3)),
                ('day_month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('seconde', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app1.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app1.user')),
            ],
        ),
    ]
